name: PHP SDK CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.4', '8.2', '8.3']
    name: run tests @${{ matrix.php }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6
        with:
          command: update
          args: --prefer-lowest
          php_version: ${{ matrix.php }}
          version: "2.2"
      - run: "composer unit-test"
      - run: "composer quality-check"
